theme: devopsdays-theme
baseURL: https://www.devopsdays.org/
languageCode: en-us
defaultContentLanguage: en
GoogleAnalytics: UA-9713393-1
title: DevOpsDays
buildDrafts: false
canonifyURLs: false
dataDir: data
archetypeDir: archetypes
disableKinds: ["taxonomy"]
enableEmoji: true
paginatePath: blog
markup:
  goldmark:
    renderer:
      unsafe: true
languages:
  en:
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    weight: 0
    params:
      flag: ":us:"
  pt-br:
    disabled: false
    languageCode: pt-BR
    languageName: português (Brasil)
    weight: 1
    params:
      flag: ":brazil:"
  fr:
    disabled: false
    languageCode: fr
    languageName: Français
    params:
      flag: ":fr:"

permalinks:
  page: /:filename/
  blog: /blog/:year/:month/:day/:title/
  speaking: /:filename/

params:
  Facebook: //www.facebook.com/group.php?gid=106761636771
  Twitter: http://www.twitter.com/devopsdays
  Linkedin: http://www.linkedin.com/groups?home=&gid=2445279
  Groups: http://groups.google.com/group/devopsdays
  GoogleMapsAPI: AIzaSyA1WhgJirbPSYxMCWRD14IP90A4yLY4vxE
